# Docker will need sudo permissions
sudo: required
# Travis will need to have docker installed
services:
  - docker

before_install:
  # Build the docker image with a tag
  - docker build -t giedrius-timinskis/study--react-in-docker -f Dockerfile.dev .

script:
  # Tell Travis how to run the tests
  # It expects some output from the command so we have to run a specific npm command that will force process exit
  - docker run giedrius-timinskis/study--react-in-docker npm run test:ci